SELECT CONCAT("/home/grep/src/", CONCAT(F.BOARD_ID, CONCAT("/", CONCAT(F.FILE_ID, CONCAT(F.FILE_NAME, F.FILE_EXT))))) AS FILE_PATH
FROM USED_GOODS_BOARD AS B
JOIN USED_GOODS_FILE AS F ON B.BOARD_ID = F.BOARD_ID
WHERE B.BOARD_ID = (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD AS B
    ORDER BY B.VIEWS DESC LIMIT 1
)
ORDER BY F.FILE_ID DESC