-- 코드를 입력하세요
SELECT i.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS, ROUND(AVG(r.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO as i
JOIN REST_REVIEW as r ON i.REST_ID = r.REST_ID
WHERE ADDRESS LIKE "서울%"
GROUP BY r.REST_ID
ORDER BY AVG(r.REVIEW_SCORE) DESC, i.FAVORITES DESC